server:
  port: ${SERVER_PORT}

spring:
  application:
    name: MickleMuckle
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: ${ORACLE_DB_URL}
    username: ${ORACLE_DB_USERNAME}
    password: ${ORACLE_DB_PASSWORD}
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true
    database: oracle
    #database-platform: org.hibernate.dialect.Oracle12Dialect
    database-platform: org.hibernate.dialect.OracleDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

logging:
  level:
    hibernate: info
    '[org.springframework]': warn
    '[com.mmk]': debug
    '[org.springframework.boot]': info
  file:
    name: ${LOG_FILE_PATH}/application.log
